# Generated by Django 4.2.6 on 2023-10-23 14:57

from django.db import migrations

def update_ampm_to_pm(apps, schema_editor):
    YourModel = apps.get_model('branch', 'Courierform')
    YourModel.objects.filter(ampm='am').update(ampm='pm')
class Migration(migrations.Migration):

    dependencies = [
        ('branch', '0001_initial'),
    ]

    operations = [
    ]
